apiVersion: v1
kind: Config
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkE0b19TV3UwcG1qZUFIV3lpOWZrM3NZRWVGVC1nbzNLU1RkRlRHVkFjZ2sifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzI4MzMwNzI3LCJpYXQiOjE3MjgyNDQzMjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiY2Q4NTVjM2ItNWRlOS00ZmI1LWIzODktMmUzNDZjZmI1M2IyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImY3MmI3ZWU2LTFjNjItNDM5Yy05MWM5LTA3ODRhM2I5OTk5NSJ9fSwibmJmIjoxNzI4MjQ0MzI3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.DaOCUrCAVwT6Nf6lBTlEljdSSAJuBbzqxdP0B_2ozvNHGYTjf533CWpmodYrJOiPNYliai1PAnSRqLB0TNXL8yvTzTVeaRu60P4ZoYP6CtFEQrDHLGgFPW0J7JUUGljiTZopQlBVIvQen_Ud0hwxiPpUJBcn_0kw55mDWOsGAXkeG_Ozjg0909RKmTQmD31_nVpZn1vkICspfIADEYWpdpEBXvHOBF3EVHb1anRcAAjMwlY-cYOAkdN83eJyEkVJR-ZI90F4KAHNr8mS7iwW5mZe7ZvxwIsegS1pfZw0rlWbF8B1HVavBnMMFtDJR7om1DqaEsBhPrHZVdD7vVwM0w
clusters:
- cluster:
    certificate-authority: /home/kaa24/.minikube/ca.crt
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: cd
  name: minikube-cd-context
current-context: minikube-cd-context
