apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-parameters
  namespace: homework
data:
  key1: value1
  key2: value2
  file: |
    This is a sample file content
    that will be accessible via /conf/file