apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm -f /homework/index.html"]
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/homework/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/homework"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}